.TH PWDINFO "1" "January 30" "Pwdinfo" "General Commands Manual"


.SH NAME

pwdinfo \- get password information


.SH SYNOPSIS

.B pwdinfo

.SH DESCRIPTION

No flags available for this utility

.SH EXAMPLES

.TP
pwdinfo
Prompt for password and output info about it


.SH AUTHOR

Written by Ari Archer <ari.web.xyz@gmail.com>


.SH "REPORTING BUGS"

Report any bugs or feature requests to https://ari-web.xyz/gh/pwdtools issues

