.TH PWDINFO "1" "April 9" "Pwdzxc" "General Commands Manual"


.SH NAME

pwdzxc \- get realistic password information using zxcvbn


.SH SYNOPSIS

.B pwdzxc

.SH DESCRIPTION

No flags available for this utility

.SH EXAMPLES

.TP
pwdzxc
Prompt for password and output info about it


.SH AUTHOR

Written by Ari Archer <ari.web.xyz@gmail.com>


.SH "REPORTING BUGS"

Report any bugs or feature requests to https://ari-web.xyz/gh/pwdtools issues

